name: parivartan
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.2
  cloud_firestore: ^6.0.0
  image_picker: ^1.2.0
  shared_preferences: ^2.5.3
  razorpay_flutter: ^1.3.5

  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  google_fonts: ^6.1.0
  qr_flutter: ^4.1.0
  upi_india: ^3.0.1
  firebase_database: ^12.0.2
  fl_chart: ^0.68.0

  flutter_svg: ^2.0.9
  url_launcher: ^6.2.2
  font_awesome_flutter: ^10.6.0
  video_player: ^2.8.1
  chewie: ^1.7.5
  flutter_animate: ^4.3.0
  http: ^1.5.0
  provider: ^6.1.5+1
  firebase_messaging: ^16.0.3
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Nss_Logo.jpg
